
import { Cuisine } from '../types';

// NOTE: All images are now generated by AI on app startup.
// The empty 'image' fields will be populated dynamically.

export const initialCuisines: Cuisine[] = [
  {
    id: 1,
    name: 'Italian',
    description: 'Savor the rich, comforting flavors of vegetarian Italian cuisine, from hearty pastas to fresh, vibrant salads.',
    image: '',
    recipes: [
      {
        id: 101,
        name: 'Mushroom Risotto',
        image: '',
        ingredients: ['1L vegetable stock', '1 tbsp olive oil', '1 onion, chopped', '2 garlic cloves, crushed', '250g mushrooms, sliced', '300g risotto rice', '125ml white wine', '50g Parmesan, grated', 'Handful of parsley, chopped'],
        instructions: ['Heat the stock.', 'Sauté onion and garlic.', 'Add mushrooms and cook until soft.', 'Stir in rice, then add wine.', 'Gradually add stock, stirring constantly.', 'Stir in Parmesan and parsley.'],
        youtubeLink: 'https://www.youtube.com/results?search_query=vegetarian+mushroom+risotto+recipe',
      },
      {
        id: 102,
        name: 'Caprese Salad',
        image: '',
        ingredients: ['4 ripe tomatoes', '200g fresh mozzarella', 'Fresh basil leaves', 'Extra virgin olive oil', 'Balsamic glaze', 'Salt and pepper'],
        instructions: ['Slice tomatoes and mozzarella.', 'Arrange on a platter, alternating slices.', 'Tuck basil leaves in between.', 'Drizzle with olive oil and balsamic glaze.', 'Season with salt and pepper.'],
        youtubeLink: 'https://www.youtube.com/results?search_query=caprese+salad+recipe',
      },
      {
        id: 103,
        name: 'Pesto Pasta',
        image: '',
        ingredients: ['300g pasta', '2 cups fresh basil', '1/2 cup pine nuts', '2 garlic cloves', '1/2 cup grated Parmesan', '1/2 cup olive oil', 'Salt and pepper'],
        instructions: ['Cook pasta according to package directions.', 'Blend basil, pine nuts, garlic, and Parmesan in a food processor.', 'Slowly pour in olive oil while blending until smooth.', 'Drain pasta, reserving some pasta water.', 'Toss pasta with pesto, adding pasta water to thin if needed.'],
        youtubeLink: 'https://www.youtube.com/results?search_query=pesto+pasta+recipe',
      },
       {
        id: 104,
        name: 'Eggplant Parmesan',
        image: '',
        ingredients: ['2 large eggplants', '1 cup breadcrumbs', '1/2 cup grated Parmesan', '2 cups marinara sauce', '200g mozzarella, sliced', '1/4 cup olive oil'],
        instructions: ['Slice eggplant, salt it, and let it sit for 30 mins.', 'Rinse and pat dry the eggplant slices.', 'Dip slices in oil, then in a mix of breadcrumbs and Parmesan.', 'Bake at 200°C (400°F) for 20 minutes.', 'Layer baked eggplant with marinara and mozzarella in a baking dish.', 'Bake for another 20 minutes until bubbly and golden.'],
        youtubeLink: 'https://www.youtube.com/results?search_query=eggplant+parmesan+recipe',
      },
    ],
  },
  {
    id: 2,
    name: 'Indian',
    description: 'Explore the aromatic and diverse world of Indian vegetarian dishes, bursting with spices and flavor.',
    image: '',
    recipes: [
      {
        id: 201,
        name: 'Palak Paneer',
        image: '',
        ingredients: ['500g spinach', '250g paneer, cubed', '1 onion, finely chopped', '2 tomatoes, pureed', '1 tbsp ginger-garlic paste', '1 tsp turmeric powder', '1 tsp garam masala', '50ml cream', '2 tbsp oil'],
        instructions: ['Blanch and puree spinach.', 'Sauté paneer cubes until golden.', 'In a pan, cook onion, ginger-garlic paste, and tomato puree.', 'Add spices and cook for 5 minutes.', 'Stir in spinach puree and paneer.', 'Finish with cream and garam masala.'],
        youtubeLink: 'https://www.youtube.com/results?search_query=palak+paneer+recipe',
      },
       {
        id: 202,
        name: 'Chole (Chickpea Curry)',
        image: '',
        ingredients: ['2 cups boiled chickpeas', '2 onions, finely chopped', '3 tomatoes, pureed', '1 tbsp ginger-garlic paste', '1 tsp cumin seeds', '2 tsp chole masala', '1 tsp coriander powder', 'Salt to taste', '2 tbsp oil'],
        instructions: ['Heat oil, add cumin seeds.', 'Sauté onions until golden brown.', 'Add ginger-garlic paste and cook.', 'Add tomato puree and spices.', 'Cook until oil separates.', 'Add chickpeas, water, and simmer for 15 minutes.'],
        youtubeLink: 'https://www.youtube.com/results?search_query=chole+recipe',
      },
      {
        id: 203,
        name: 'Aloo Gobi',
        image: '',
        ingredients: ['1 medium cauliflower, cut into florets', '3 medium potatoes, cubed', '1 onion, chopped', '1 tomato, chopped', '1 tsp turmeric powder', '1 tsp cumin seeds', '1 tsp coriander powder', '2 tbsp oil'],
        instructions: ['Heat oil, add cumin seeds.', 'Sauté onions until translucent.', 'Add potatoes and cook for 5 minutes.', 'Add cauliflower, tomato, and spices.', 'Cover and cook until vegetables are tender, stirring occasionally.'],
        youtubeLink: 'https://www.youtube.com/results?search_query=aloo+gobi+recipe',
      },
      {
        id: 204,
        name: 'Vegetable Biryani',
        image: '',
        ingredients: ['1 cup basmati rice, soaked', '2 cups mixed vegetables (carrots, peas, beans)', '1 onion, thinly sliced', '1/2 cup yogurt', '1 tbsp biryani masala', '1/4 cup chopped mint and cilantro', '2 tbsp oil'],
        instructions: ['Par-cook the basmati rice and set aside.', 'Sauté onions until golden brown.', 'Add vegetables, yogurt, and biryani masala, cook for 10 minutes.', 'Layer the rice and vegetable mixture in a pot.', 'Top with mint, cilantro, and fried onions.', 'Cover and cook on low heat (dum) for 20 minutes.'],
        youtubeLink: 'https://www.youtube.com/results?search_query=vegetable+biryani+recipe',
      },
    ],
  },
  {
    id: 3,
    name: 'Mexican',
    description: 'Enjoy festive and fresh vegetarian Mexican food, perfect for sharing and celebrating.',
    image: '',
    recipes: [
      {
        id: 301,
        name: 'Black Bean Tacos',
        image: '',
        ingredients: ['8 taco shells', '1 can black beans, rinsed', '1 red onion, diced', '1 avocado, sliced', '1 cup corn salsa', '1/2 cup cilantro, chopped', 'Lime wedges'],
        instructions: ['Warm taco shells.', 'Mash half of the black beans lightly.', 'Fill shells with beans, onion, avocado, and corn salsa.', 'Top with cilantro.', 'Serve with lime wedges.'],
        youtubeLink: 'https://www.youtube.com/results?search_query=vegetarian+black+bean+tacos+recipe',
      },
       {
        id: 302,
        name: 'Vegetarian Enchiladas',
        image: '',
        ingredients: ['8 corn tortillas', '1 can black beans', '1 cup cooked corn', '1 cup spinach', '2 cups enchilada sauce', '1 cup shredded cheese (cheddar or monterey jack)', '1/4 cup chopped onions'],
        instructions: ['Preheat oven to 190°C (375°F).', 'In a bowl, mix black beans, corn, spinach, and half the cheese.', 'Warm tortillas to make them pliable.', 'Spoon filling into each tortilla, roll up, and place seam-side down in a baking dish.', 'Pour enchilada sauce over the top and sprinkle with remaining cheese.', 'Bake for 20 minutes until melted and bubbly.'],
        youtubeLink: 'https://www.youtube.com/results?search_query=vegetarian+enchiladas+recipe',
      },
    ],
  },
  {
    id: 4,
    name: 'Thai',
    description: 'A perfect balance of sweet, sour, salty, and spicy in every vegetarian Thai dish.',
    image: '',
    recipes: [
        {
            id: 401,
            name: 'Vegetable Green Curry',
            image: '',
            ingredients: ['2 tbsp green curry paste', '1 can coconut milk', '1 cup mixed vegetables (broccoli, carrots, bell peppers)', '100g firm tofu, cubed', '1 tbsp soy sauce', '1 tsp sugar', 'Fresh basil leaves'],
            instructions: ['Sauté curry paste in a little coconut milk.', 'Add the rest of the coconut milk and bring to a simmer.', 'Add vegetables and tofu, cook until tender.', 'Stir in soy sauce and sugar.', 'Garnish with fresh basil.'],
            youtubeLink: 'https://www.youtube.com/results?search_query=vegetarian+thai+green+curry+recipe',
        },
        {
            id: 402,
            name: 'Vegetarian Pad Thai',
            image: '',
            ingredients: ['200g rice noodles', '200g firm tofu, pressed and cubed', '2 tbsp soy sauce', '1 tbsp tamarind paste', '1 tbsp sugar', '1 tbsp lime juice', '2 cloves garlic, minced', '1 cup bean sprouts', '1/4 cup crushed peanuts'],
            instructions: ['Soak rice noodles in warm water until soft, then drain.', 'Pan-fry tofu until golden.', 'In a wok, sauté garlic, then add the drained noodles and tofu.', 'In a small bowl, mix soy sauce, tamarind paste, sugar, and lime juice.', 'Pour sauce over noodles and toss to coat.', 'Stir in bean sprouts and serve topped with crushed peanuts.'],
            youtubeLink: 'https://www.youtube.com/results?search_query=vegetarian+pad+thai+recipe',
        },
    ]
  },
  {
    id: 5,
    name: 'Chinese',
    description: 'Discover the diverse regional flavors of vegetarian Chinese cooking, from stir-fries to dumplings.',
    image: '',
    recipes: [
        {
            id: 501,
            name: 'Vegetable Chow Mein',
            image: '',
            ingredients: ['200g egg-free noodles', '1 tbsp soy sauce', '1 tbsp sesame oil', '2 cups shredded vegetables (cabbage, carrots, bell peppers)', '2 cloves garlic, minced', '1 tbsp vegetable oil'],
            instructions: ['Boil noodles according to package directions.', 'Heat vegetable oil in a wok.', 'Sauté garlic and vegetables until crisp-tender.', 'Add cooked noodles, soy sauce, and sesame oil.', 'Toss to combine and serve hot.'],
            youtubeLink: 'https://www.youtube.com/results?search_query=vegetable+chow+mein+recipe',
        },
        {
            id: 502,
            name: 'Mapo Tofu (Vegetarian)',
            image: '',
            ingredients: ['1 block silken tofu, cubed', '1 tbsp doubanjiang (fermented broad bean paste)', '1 tsp fermented black beans, minced', '2 cloves garlic, minced', '1 tbsp soy sauce', '1 tsp cornstarch mixed with 2 tsp water', 'Chopped scallions for garnish'],
            instructions: ['Gently simmer tofu cubes in salted water for a minute, then drain.', 'In a wok, stir-fry doubanjiang, fermented black beans, and garlic until fragrant.', 'Add 1/2 cup of water or vegetable broth and soy sauce, bring to a simmer.', 'Gently add the tofu cubes.', 'Thicken the sauce with the cornstarch slurry.', 'Garnish with scallions before serving.'],
            youtubeLink: 'https://www.youtube.com/results?search_query=vegetarian+mapo+tofu+recipe',
        },
    ]
  },
  {
    id: 6,
    name: 'Japanese',
    description: 'Experience the clean, delicate, and artful presentation of vegetarian Japanese cuisine.',
    image: '',
    recipes: [
        {
            id: 601,
            name: 'Avocado Sushi Rolls',
            image: '',
            ingredients: ['2 cups sushi rice, cooked', '3 sheets nori', '1 avocado, sliced', '1 cucumber, julienned', 'Soy sauce, for serving', 'Pickled ginger, for serving', 'Wasabi, for serving'],
            instructions: ['Place a nori sheet on a bamboo rolling mat.', 'Spread a thin layer of sushi rice over the nori.', 'Arrange avocado and cucumber slices on the rice.', 'Roll tightly using the mat.', 'Slice the roll into pieces and serve with condiments.'],
            youtubeLink: 'https://www.youtube.com/results?search_query=avocado+sushi+roll+recipe',
        },
        {
            id: 602,
            name: 'Vegetable Tempura',
            image: '',
            ingredients: ['1 cup mixed vegetables (sweet potato, broccoli, zucchini, bell pepper)', '1 cup tempura flour', '1 cup ice-cold water', 'Vegetable oil for frying', 'Dipping sauce (tentsuyu)'],
            instructions: ['Slice vegetables into bite-sized pieces.', 'In a bowl, lightly mix tempura flour and ice-cold water. Do not overmix; lumps are okay.', 'Heat oil to 180°C (350°F).', 'Dip vegetables in batter and fry until lightly golden and crispy.', 'Drain on a wire rack and serve immediately with dipping sauce.'],
            youtubeLink: 'https://www.youtube.com/results?search_query=vegetable+tempura+recipe',
        },
    ]
  },
  {
    id: 7,
    name: 'Mediterranean',
    description: 'Fresh vegetables, whole grains, and healthy fats are the stars of this sunny cuisine.',
    image: '',
    recipes: [
        {
            id: 701,
            name: 'Falafel Wraps',
            image: '',
            ingredients: ['6-8 pre-made falafel balls', '4 pita breads', '1 cup hummus', '1 cup chopped lettuce', '1 tomato, diced', '1/2 cucumber, diced', 'Tahini sauce for drizzling'],
            instructions: ['Warm pita breads.', 'Spread a generous layer of hummus on each pita.', 'Place falafel balls on top and lightly crush them.', 'Add lettuce, tomato, and cucumber.', 'Drizzle with tahini sauce and wrap tightly.'],
            youtubeLink: 'https://www.youtube.com/results?search_query=falafel+wrap+recipe',
        },
    ]
  },
   {
    id: 8,
    name: 'Korean',
    description: 'Bold, savory, and often spicy, vegetarian Korean food is a feast for the senses.',
    image: '',
    recipes: [
        {
            id: 801,
            name: 'Vegetable Bibimbap',
            image: '',
            ingredients: ['2 cups cooked rice', '1 cup spinach, blanched', '1 carrot, julienned', '1 zucchini, julienned', '1 cup mushrooms, sliced', '100g firm tofu', '1 tbsp gochujang (Korean chili paste)', '1 tsp sesame oil', 'Soy sauce'],
            instructions: ['Sauté each vegetable and tofu separately with a little soy sauce.', 'Arrange the cooked rice in a bowl.', 'Top with the sautéed vegetables and tofu in sections.', 'Add a dollop of gochujang in the center.', 'Drizzle with sesame oil before serving. Mix well before eating.'],
            youtubeLink: 'https://www.youtube.com/results?search_query=vegetarian+bibimbap+recipe',
        },
    ]
  },
];
